spring:
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    username: username
    url: jdbc:mysql://localhost:3306/dshinghis_khan?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true
    username: username
    password: password
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        enable_lazy_load_no_trans: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
#    show-sql: true
logging:
  path: /path/to/logs
google-maps-key: googleMapsKey
upload-directory: /Upload/Directory
sms-service-login: login
sms-service-password: password
sms-service-sender: TEST-SMS
mail-from: mail-from
