spring:
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    username: Khan
    url: jdbc:mysql://localhost:3306/dshinghis_khan?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    password: Diogenes-412
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true
    username: tarificationSquad
    password: Fgsfds12
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        enable_lazy_load_no_trans: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
#    show-sql: true
logging:
  path: /Users/Roman 1/Desktop/exchange/logs
google-maps-key: AIzaSyCbWvhz07RoOhD8qs9dFtIxf3W4d_qQjAk
upload-directory: /Users/Roman 1/Desktop/uploads/
sms-service-login: iSosnitsky
sms-service-password: Fgsfds12
sms-service-sender: TEST-SMS
mail-from: tarificationSquad@gmail.com